learn_dbt:
  target: dev
  outputs:
    dev:
      type: mysql
      server: 127.0.0.1
      port: 3306
      user: admin
      password: admin
      schema: DE4_PROJECT3 
      database: DE4_PROJECT3
